// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKlMo9EKhjRzBmeKc2AGreqFlaRYIcPY',
    appId: '1:1028753789025:web:385358018b4055eb4b5a20',
    messagingSenderId: '1028753789025',
    projectId: 'keris-il-2026',
    authDomain: 'keris-il-2026.firebaseapp.com',
    storageBucket: 'keris-il-2026.firebasestorage.app',
    measurementId: 'G-J5CMTQQ3G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBefvKoGfPr-9W7LU9i2w-57hgwzsZpDeA',
    appId: '1:1028753789025:android:d3d2a880b018b97b4b5a20',
    messagingSenderId: '1028753789025',
    projectId: 'keris-il-2026',
    storageBucket: 'keris-il-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBikFPkFW4dNg0tVKObEg33brD8uy36eCw',
    appId: '1:873580121163:ios:af6220acb9d325498bd1ce',
    messagingSenderId: '873580121163',
    projectId: 'keris-by-basudara',
    storageBucket: 'keris-by-basudara.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiKerisInfiniteLearning',
  );
}